In [1]:
%pylab inline
from scipy import stats

Populating the interactive namespace from numpy and matplotlib


In [2]:
V = np.array([3.0,3.2,3.4,3.6,3.8,4.0,4.2,4.4,4.6,4.8,5.0])*1000.
D1 = np.array([3.15,2.9,2.76,2.74,2.55,2.5,2.45,2.36,2.34,2.31,2.3])/100.
D2 = np.array([5.3,4.85,4.75,4.55,4.4,4.25,4.2,4.12,4.11,3.92,3.88])/100.
L = 13.68/100.
d1 = 2.13*10**(-10)
d2 = 1.23*10**(-10)

def f1(x):
    return x*d1/2./L

def f2(x):
    return x*d2/2./L

h = 6.6256*10**(-34)
m = 9.1091*10**(-31)
e = 1.6021*10**(-19)

def f3(x):
    return h/np.sqrt(2.*m*e*x)

In [3]:
f1(D1)

array([  2.45230263e-11,   2.25767544e-11,   2.14868421e-11,
         2.13311404e-11,   1.98519737e-11,   1.94627193e-11,
         1.90734649e-11,   1.83728070e-11,   1.82171053e-11,
         1.79835526e-11,   1.79057018e-11])

In [4]:
f2(D2)

array([  2.38267544e-11,   2.18037281e-11,   2.13541667e-11,
         2.04550439e-11,   1.97807018e-11,   1.91063596e-11,
         1.88815789e-11,   1.85219298e-11,   1.84769737e-11,
         1.76228070e-11,   1.74429825e-11])

In [5]:
f3(V)

array([  2.23906676e-11,   2.16796707e-11,   2.10323699e-11,
         2.04397895e-11,   1.98946302e-11,   1.93908870e-11,
         1.89235680e-11,   1.84884853e-11,   1.80820953e-11,
         1.77013770e-11,   1.73437366e-11])

In [6]:
f3(1000)

3.8781773913102742e-11

In [7]:
a = f3(V)-f1(D1)
b = f3(V)-f2(D2)
print max(np.abs(a)),max(np.abs(b))

2.13235870741e-12 1.43608677758e-12


In [9]:
thefit1=np.polyfit(D1,h*2.*L/np.sqrt(2.*m*e*V),1)
slope1=thefit1[0]
intercept1=thefit1[1]
print slope1, intercept1

slope11, intercept11, r_value11, p_value11, std_err11 = stats.linregress(D1,h*2.*L/np.sqrt(2.*m*e*V))
print slope11, intercept11, std_err11

thefit2=np.polyfit(D2,h*2.*L/np.sqrt(2.*m*e*V),1)
slope2=thefit2[0]
intercept2=thefit2[1]
print slope2, intercept2

slope22, intercept22, r_value22, p_value22, std_err22 = stats.linregress(D2,h*2.*L/np.sqrt(2.*m*e*V))
print slope22, intercept22, std_err22

thefit3=np.polyfit(1./np.sqrt(V),D1,1)
slope3=thefit3[0]
intercept3=thefit3[1]
print slope3, intercept3

slope33, intercept33, r_value33, p_value33, std_err33 = stats.linregress(1./np.sqrt(V),D1)
print slope33, intercept33, std_err33

thefit4=np.polyfit(1./np.sqrt(V),D2,1)
slope4=thefit4[0]
intercept4=thefit4[1]
print slope4, intercept4

slope44, intercept44, r_value44, p_value44, std_err44 = stats.linregress(1./np.sqrt(V),D2)
print slope44, intercept44, std_err44

1.60463361459e-10 1.21973433723e-12
1.60463361459e-10 1.21973433723e-12 1.19372045821e-11
1.02821322504e-10 8.39176532104e-13
1.02821322504e-10 8.39176532104e-13 6.95797193016e-12
1.9918569542 -0.00601747802705
1.9918569542 -0.00601747802705 0.148178398759
3.13415671775 -0.00609934682103
3.13415671775 -0.00609934682103 0.21209000172


In [10]:
h*2.*L/np.sqrt(2.*m*e)/1.9918569542

1.6845566367368261e-10

In [11]:
h*2.*L/np.sqrt(2.*m*e)/3.13415671775

1.0705896844995158e-10

In [12]:
d1*1.9918569542*np.sqrt(2.*m*e)/2./L

8.3775918792125242e-34

In [15]:
d1*0.148178398759*np.sqrt(2.*m*e)/2./L

6.2322655625473609e-35

In [13]:
d2*3.13415671775*np.sqrt(2.*m*e)/2./L

7.6121488166680413e-34

In [16]:
d2*0.21209000172*np.sqrt(2.*m*e)/2./L

5.1511803684757554e-35

In [14]:
(8.3775918792125242e-34 + 7.6121488166680413e-34)/2.

7.994870347940284e-34